language: objective-c

env:
  - MONO_VERSION="3.4.0"
  - MONO_VERSION="3.6.0"
  - MONO_VERSION="3.8.0"
  - MONO_VERSION="3.10.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - FSharp.AutoComplete/fake UnitTest
  - FSharp.AutoComplete/fake IntegrationTest

