language: emacs-lisp

matrix:
  fast_finish: true

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -q

install:
  - sudo apt-get install -yq libpango-1.0-0
  - sudo apt-get install -yq emacs24 emacs24-el emacs24-common-non-dfsg
  - sudo apt-get install -yq mono-complete
  - sudo apt-get install -yq fsharp

script:
  - FSharp.AutoComplete/fake BuildDebug
  - FSharp.AutoComplete/fake UnitTest
  - FSharp.AutoComplete/fake IntegrationTest
  - make -C emacs test
  - make -C emacs integration-test
  - make -C emacs check-compile

