language: emacs-lisp

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -q

install:
  - sudo apt-get install -yq libpango-1.0-0
  - sudo apt-get install -yq emacs24 emacs24-el
  - sudo apt-get install -yq emacs24 emacs24-el emacs24-common-non-dfsg
  - sudo apt-get install -yq mono-complete
  - sudo apt-get install -yq fsharp
  - git clone https://github.com/rneatherway/monodevelop-binaries.git

script:
  - make
  - make unit-test
  - make integration-test
  - make -C emacs test
  - make -C emacs integration-test
  - cd monodevelop && ./configure.sh --prefix=../monodevelop-binaries/4.2.4.35 && make build

